### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-theatrixx-xpresscue#1]
This is an unexpectedly OOP approach to writing a module. Not something I have seen before. I might have to steal some of the concepts for my own modules ;)

I don't know rxjs at all, so I dont fully follow everything it is doing, but it looks reasonable

I advise against doing this odd import https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/constants.ts#L17, in 2.3/3.0 this is guaranteed to break. I dont mind it staying, but expect some pain when the day comes that people start testing 2.3/3.0
I havent seen where this is used yet. Perhaps there is something companion can do to make these usable for you in a more generic way? Perhaps a new ui control type or somthing?

https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/instance.ts#L66 this will likely cause some performance issues. Whenever your module changes it feedback definitions, the new definitions get sent to all connected clients. This has been an issue that we have been chasing with other modules recently.

https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/actions/jump-playback.action.ts#L30 Instead of handle functions like this, you could use the callback property on the action definitions. That looks like it will better fit your coding style.

There are some floating promises that would be good to handle in some way. Even just to add a catch and log it, to avoid nodejs producing a nasty log and potentially crashing. 
Also companion isnt expectint https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/instance.ts#L25 to return a promise, so this will be left 'floating'

This won't build properly when pulled into the companion builds, because we 'abuse' some things to make a crude workflow.
* You need to have any typings in dependencies rather than devdependencies: https://github.com/bitfocus/companion-module-behringer-x32/blob/master/package.json#L50
* Build needs to be triggered in the postinstall script: https://github.com/bitfocus/companion-module-behringer-x32/blob/master/package.json#L26
* build script needs to not rely on devDependencies https://github.com/bitfocus/companion-module-behringer-x32/blob/master/package.json#L19
I think it should be possible to simulate how it would behave by doing a `yarn --prod` in your module. If it builds the dist folder and everything then it should be ok

**Comment by gabdusch** [comment]
I created PR #2 to track changes requested here.

> This is an unexpectedly OOP approach to writing a module. Not something I have seen before. I might have to steal some of the concepts for my own modules ;)

Thanks! I went for a modular and modern approach based on dependency injection because I have noticed some modules have files with 1000's of LOCs and that can get out of hand very quickly.

> I advise against doing this odd import https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/constants.ts#L17, in 2.3/3.0 this is guaranteed to break. I dont mind it staying, but expect some pain when the day comes that people start testing 2.3/3.0
I havent seen where this is used yet. Perhaps there is something companion can do to make these usable for you in a more generic way? Perhaps a new ui control type or somthing?

I use it here https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/f289dfb60e08ca8c7603fe719ac810f202e907af/src/presets/transport-controls.preset.ts#L32 for example.

I didn't want to have to import the instance everywhere as that would become messy pretty quickly. 

I guess what would be useful is if Companion simply exported those icons as static constants (they don't need to be instance members) - with proper types for us TS users, of course ;) Same goes for utility functions, regexes, etc.

> https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/instance.ts#L66 this will likely cause some performance issues. Whenever your module changes it feedback definitions, the new definitions get sent to all connected clients. This has been an issue that we have been chasing with other modules recently.

I understand and I was worried this might be the case. We do this so that dropdown menus in the feedback configurations are updated dynamically when there is a state change on the device.

In order to offer a rich UX, it was important that we don't force the users to enter GUIDs and other non-user-friendly strings in the action/feedback configuration. For example, we can display a dropdown with all media assets on our player, that will automatically update when a new file is uploaded, or renamed, etc.

What would be awesome would be to have a way to add reactive options which can then be updated as data changes. For example, instead of accepting a static array of `SomeCompanionInputField` in `CompanionFeedbackBase#options`, accept an `Observable<SomeCompanionInputField[]>` as well. I realize this is a major structural change, but would be happy to discuss ideas further :) 

In the meantime, I am not sure how to handle this. Perhaps we could have a configuration setting in our module to disable (or at least throttle) frequent updates, if it causes performance issues on slower machines?

> https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/actions/jump-playback.action.ts#L30 Instead of handle functions like this, you could use the callback property on the action definitions. That looks like it will better fit your coding style.

Noted, I will look into it. But is there any downside to our current approach?

> There are some floating promises that would be good to handle in some way. Even just to add a catch and log it, to avoid nodejs producing a nasty log and potentially crashing.
Also companion isnt expectint https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/instance.ts#L25 to return a promise, so this will be left 'floating'

I tried to remove floating promises in d0a92196188326c3d379d0296ef11813968ec396, let me know if you still see some I forgot.

> You need to have any typings in dependencies rather than devdependencies: https://github.com/bitfocus/companion-module-behringer-x32/blob/master/package.json#L50

I don't think I have any of those.

> Build needs to be triggered in the postinstall script: https://github.com/bitfocus/companion-module-behringer-x32/blob/master/package.json#L26

Done in 3592610f052d5870d3902c6f50780fd22e766430

> build script needs to not rely on devDependencies https://github.com/bitfocus/companion-module-behringer-x32/blob/master/package.json#L19

Done in 3592610f052d5870d3902c6f50780fd22e766430

> I think it should be possible to simulate how it would behave by doing a yarn --prod in your module. If it builds the dist folder and everything then it should be ok

It builds okay with the above changes!

**Comment by Julusian** [comment]
> Thanks! I went for a modular and modern approach based on dependency injection because I have noticed some modules have files with 1000's of LOCs and that can get out of hand very quickly.

Yeah, most modules do end up with hugely long files. I havent yet put the effort into figuring out a properly solution for splitting them up myself, especially when wanting to keep typescript happy

> I guess what would be useful is if Companion simply exported those icons as static constants (they don't need to be instance members) - with proper types for us TS users, of course ;) Same goes for utility functions, regexes, etc.

Ive noticed that another module is already importing this file, so it will be harder to impove than I was hoping... Its probably not worth worrying about for now then. 3.0 is already going to introduce a rewritten module api, and has a backwards compatibility layer which can include things like this bad import, so it may as well stay as is for 2.2 

> What would be awesome would be to have a way to add reactive options which can then be updated as data changes. For example, instead of accepting a static array of `SomeCompanionInputField` in `CompanionFeedbackBase#options`, accept an `Observable<SomeCompanionInputField[]>` as well. I realize this is a major structural change, but would be happy to discuss ideas further :)

I dont remember if there is an issue currently open for this, but it has been suggested before (https://github.com/bitfocus/companion/issues/1635 is related but not entirely the same). The challenge is going to become how to make this work in a fluid way. With many users using the ui over a vpn, anything too dynamic like this will mean that actions using these reactive/dynamic options will take some extra ms to load. There are many ways this could be approached, but its figuring out which is the right one for us, and then making the ui feel right with that method.

> In order to offer a rich UX, it was important that we don't force the users to enter GUIDs and other non-user-friendly strings in the action/feedback configuration. For example, we can display a dropdown with all media assets on our player, that will automatically update when a new file is uploaded, or renamed, etc.
> 
> In the meantime, I am not sure how to handle this. Perhaps we could have a configuration setting in our module to disable (or at least throttle) frequent updates, if it causes performance issues on slower machines?

Having updating dropdown options like this is not uncommon, and is not discouraged. I only have a problem with how often it will update. It looked to me that every you say that any feedback value changed, it will emit this update. If you could make it simply do a check to make sure it is likely that the list of guids has changed before deciding to do that call then I will be happy.

For example, in `bmd-atem` it checks 'if the state update affected something do with the input properties', and only then does it update the list of action and feedback definitions. I dont check if a name actually did change (out of laziness), but this stops things which are clearly not related to the input names from doing the extra work.

> > [https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/actions/jump-playback.action.ts#L30](https://github.com/bitfocus/companion-module-theatrixx-xpresscue/blob/main/src/actions/jump-playback.action.ts?rgh-link-date=2022-05-04T20%3A46%3A43Z#L30) Instead of handle functions like this, you could use the callback property on the action definitions. That looks like it will better fit your coding style.
> 
> Noted, I will look into it. But is there any downside to our current approach?

No, there is nothing wrong with that approach.

> > I think it should be possible to simulate how it would behave by doing a yarn --prod in your module. If it builds the dist folder and everything then it should be ok
> 
> It builds okay with the above changes!

Perfect

**Comment by gabdusch** [comment]
@Julusian see 2aebdc706f65903c4cec55357e47baf31f0a1d0d, this should address most performance concerns.

**Comment by Julusian** [comment]
Yeah Im happy :)

**Comment by gabdusch** [comment]
@Julusian Done! I just deleted and re-tagged `v1.0.0` on `main:HEAD` - as I realized I probably should have waited until after this review to release anyway ;)
